# Spring Config, Persistance, Database
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/db_commerce?serverTimezone=Asia/Jakarta&useLegacyDatetimeCode=false
    username: ucommerce
    password: 123qwe
  jpa: 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
